export enum Countries {
  Deutschland = 'Germany',
  Großbritanien = 'United Kingdom',
  Frankreich = 'France',
  Niederlande = 'Netherlands',
  Italien = 'Italy',
  Österreich = 'Austria',
  Schweiz = 'Switzerland',
  Polen = 'Poland',
  Tschechien = 'Czechia',
  Dänemark = 'Denmark',
  Norwegen = 'Norway',
  Schweden = 'Sweden',
  Finnland = 'Finland',
  Spanien = 'Spain',
  Portugal = 'Portugal',
  Russland = 'Russia',
  USA = 'US',
  China = 'China',
}
